#!/bin/bash
sudo pip3 install requests
sudo pip3 install BeautifulSoup
sudo pip3 install selenium
sudo pip3 install scapy
sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
tar -xvzf geckodriver-v0.23.0-linux64.tar.gz
sudo chmod +x geckodriver
sudo mv geckodriver /usr/local/bin/
sudo rm geckodriver-v0.23.0-linux64.tar.gz
